# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.AccountListAccounts do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :account_name,
    :owner_email,
    :account_type,
    :seats,
    :subscription_start_time,
    :subscription_end_time,
    :created_at
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :account_name => String.t(),
          :owner_email => String.t(),
          :account_type => String.t(),
          :seats => integer(),
          :subscription_start_time => DateTime.t(),
          :subscription_end_time => DateTime.t(),
          :created_at => DateTime.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.AccountListAccounts do
  def decode(value, _options) do
    value
  end
end
