# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.AccountSettingsRecording do
  @moduledoc """
  Account Settings: Recording.
  """

  @derive [Poison.Encoder]
  defstruct [
    :local_recording,
    :cloud_recording,
    :record_speaker_view,
    :record_gallery_view,
    :record_audio_file,
    :save_chat_text,
    :show_timestamp,
    :recording_audio_transcript,
    :auto_recording,
    :cloud_recording_download,
    :cloud_recording_download_host,
    :account_user_access_recording,
    :auto_delete_cmr,
    :auto_delete_cmr_days
  ]

  @type t :: %__MODULE__{
          :local_recording => boolean(),
          :cloud_recording => boolean(),
          :record_speaker_view => boolean(),
          :record_gallery_view => boolean(),
          :record_audio_file => boolean(),
          :save_chat_text => boolean(),
          :show_timestamp => boolean(),
          :recording_audio_transcript => boolean(),
          :auto_recording => String.t(),
          :cloud_recording_download => boolean(),
          :cloud_recording_download_host => boolean(),
          :account_user_access_recording => boolean(),
          :auto_delete_cmr => boolean(),
          :auto_delete_cmr_days => integer()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.AccountSettingsRecording do
  def decode(value, _options) do
    value
  end
end
