# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.AccountSettingsSecurity do
  @moduledoc """
  Account Settings: Security.
  """

  @derive [Poison.Encoder]
  defstruct [
    :admin_change_name_pic,
    :import_photos_from_devices,
    :hide_billing_info
  ]

  @type t :: %__MODULE__{
          :admin_change_name_pic => boolean(),
          :import_photos_from_devices => boolean(),
          :hide_billing_info => boolean()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.AccountSettingsSecurity do
  def decode(value, _options) do
    value
  end
end
