# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.AccountsaccountIdsettingsScheduleMeting do
  @moduledoc """
  Account Settings: Schedule Meeting.
  """

  @derive [Poison.Encoder]
  defstruct [
    :host_video,
    :participant_video,
    :audio_type,
    :join_before_host,
    :enforce_login,
    :enforce_login_with_domains,
    :enforce_login_domains,
    :not_store_meeting_topic,
    :force_pmi_jbh_password,
    :use_pmi_for_scheduled_meetings,
    :use_pmi_for_instant_meetings
  ]

  @type t :: %__MODULE__{
          :host_video => boolean(),
          :participant_video => boolean(),
          :audio_type => String.t(),
          :join_before_host => boolean(),
          :enforce_login => boolean(),
          :enforce_login_with_domains => boolean(),
          :enforce_login_domains => String.t(),
          :not_store_meeting_topic => boolean(),
          :force_pmi_jbh_password => boolean(),
          :use_pmi_for_scheduled_meetings => boolean(),
          :use_pmi_for_instant_meetings => boolean()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.AccountsaccountIdsettingsScheduleMeting do
  def decode(value, _options) do
    value
  end
end
