# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.AccountsaccountIdsettingsTsp do
  @moduledoc """
  Account Settings: TSP.
  """

  @derive [Poison.Encoder]
  defstruct [
    :call_out,
    :call_out_countries,
    :show_international_numbers_link,
    :display_toll_free_numbers
  ]

  @type t :: %__MODULE__{
          :call_out => boolean(),
          :call_out_countries => [map],
          :show_international_numbers_link => boolean(),
          :display_toll_free_numbers => boolean()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.AccountsaccountIdsettingsTsp do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:call_out_countries, :list, :map, options)
  end
end
