# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.AccountPlans do
  @moduledoc """
  Account Plans object.
  """

  @derive [Poison.Encoder]
  defstruct [
    :plan_base,
    :plan_zoom_rooms,
    :plan_room_connector,
    :plan_large_meeting,
    :plan_webinar,
    :plan_recording,
    :plan_audio
  ]

  @type t :: %__MODULE__{
          :plan_base => InlineResponse2003PlanBase,
          :plan_zoom_rooms => InlineResponse2003PlanZoomRooms,
          :plan_room_connector => InlineResponse2003PlanZoomRooms,
          :plan_large_meeting => [InlineResponse2003PlanZoomRooms],
          :plan_webinar => [InlineResponse2003PlanZoomRooms],
          :plan_recording => String.t(),
          :plan_audio => InlineResponse2003PlanAudio
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.AccountPlans do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:plan_base, :struct, ZoomAPI.Model.InlineResponse2003PlanBase, options)
    |> deserialize(
      :plan_zoom_rooms,
      :struct,
      ZoomAPI.Model.InlineResponse2003PlanZoomRooms,
      options
    )
    |> deserialize(
      :plan_room_connector,
      :struct,
      ZoomAPI.Model.InlineResponse2003PlanZoomRooms,
      options
    )
    |> deserialize(
      :plan_large_meeting,
      :list,
      ZoomAPI.Model.InlineResponse2003PlanZoomRooms,
      options
    )
    |> deserialize(:plan_webinar, :list, ZoomAPI.Model.InlineResponse2003PlanZoomRooms, options)
    |> deserialize(:plan_audio, :struct, ZoomAPI.Model.InlineResponse2003PlanAudio, options)
  end
end
