# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.AccountSettingsZoomRooms do
  @moduledoc """
  Account Settings: Zoom Rooms.
  """

  @derive [Poison.Encoder]
  defstruct [
    :upcoming_meeting_alert,
    :start_airplay_manually,
    :weekly_system_restart,
    :list_meetings_with_calendar,
    :zr_post_meeting_feedback,
    :ultrasonic,
    :force_private_meeting,
    :hide_host_information,
    :cmr_for_instant_meeting,
    :auto_start_stop_scheduled_meetings
  ]

  @type t :: %__MODULE__{
          :upcoming_meeting_alert => boolean(),
          :start_airplay_manually => boolean(),
          :weekly_system_restart => boolean(),
          :list_meetings_with_calendar => boolean(),
          :zr_post_meeting_feedback => boolean(),
          :ultrasonic => boolean(),
          :force_private_meeting => boolean(),
          :hide_host_information => boolean(),
          :cmr_for_instant_meeting => boolean(),
          :auto_start_stop_scheduled_meetings => boolean()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.AccountSettingsZoomRooms do
  def decode(value, _options) do
    value
  end
end
