# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.AccountsaccountIdsettingsEmailNotification do
  @moduledoc """
  Account Settings: Notification.
  """

  @derive [Poison.Encoder]
  defstruct [
    :cloud_recording_avaliable_reminder,
    :jbh_reminder,
    :cancel_meeting_reminder,
    :low_host_count_reminder,
    :alternative_host_reminder
  ]

  @type t :: %__MODULE__{
          :cloud_recording_avaliable_reminder => boolean(),
          :jbh_reminder => boolean(),
          :cancel_meeting_reminder => boolean(),
          :low_host_count_reminder => boolean(),
          :alternative_host_reminder => boolean()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.AccountsaccountIdsettingsEmailNotification do
  def decode(value, _options) do
    value
  end
end
