# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.AccountList do
  @moduledoc """
  List of Accounts.
  """

  @derive [Poison.Encoder]
  defstruct [
    :accounts,
    :page_count,
    :page_number,
    :page_size,
    :total_records
  ]

  @type t :: %__MODULE__{
          :accounts => [AccountListAccounts],
          :page_count => integer(),
          :page_number => integer(),
          :page_size => integer(),
          :total_records => integer()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.AccountList do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:accounts, :list, ZoomAPI.Model.AccountListAccounts, options)
  end
end
