# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.AccountsaccountIdsettingsIntegration do
  @moduledoc """
  Account Settings: Integration.
  """

  @derive [Poison.Encoder]
  defstruct [
    :google_calendar,
    :google_drive,
    :dropbox,
    :box,
    :microsoft_one_drive,
    :kubi
  ]

  @type t :: %__MODULE__{
          :google_calendar => boolean(),
          :google_drive => boolean(),
          :dropbox => boolean(),
          :box => boolean(),
          :microsoft_one_drive => boolean(),
          :kubi => boolean()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.AccountsaccountIdsettingsIntegration do
  def decode(value, _options) do
    value
  end
end
