# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.AddRoleMembers do
  @moduledoc """
  Add Role Members
  """

  @derive [Poison.Encoder]
  defstruct [
    :members
  ]

  @type t :: %__MODULE__{
          :members => [RolesroleIdmembersMembers]
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.AddRoleMembers do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:members, :list, ZoomAPI.Model.RolesroleIdmembersMembers, options)
  end
end
