# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.BillingContactRequired do
  @moduledoc """
  Billing Contact object.
  """

  @derive [Poison.Encoder]
  defstruct [
    :first_name,
    :last_name,
    :email,
    :phone_number,
    :address,
    :apt,
    :city,
    :state,
    :zip,
    :country
  ]

  @type t :: %__MODULE__{
          :first_name => String.t(),
          :last_name => String.t(),
          :email => String.t(),
          :phone_number => String.t(),
          :address => String.t(),
          :apt => String.t(),
          :city => String.t(),
          :state => String.t(),
          :zip => String.t(),
          :country => String.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.BillingContactRequired do
  def decode(value, _options) do
    value
  end
end
