# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.Body1 do
  @moduledoc """
  Account options object.
  """

  @derive [Poison.Encoder]
  defstruct [
    :share_rc,
    :room_connectors,
    :share_mc,
    :meeting_connectors,
    :pay_mode
  ]

  @type t :: %__MODULE__{
          :share_rc => boolean(),
          :room_connectors => String.t(),
          :share_mc => boolean(),
          :meeting_connectors => String.t(),
          :pay_mode => String.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.Body1 do
  def decode(value, _options) do
    value
  end
end
