# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.Body21 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :password
  ]

  @type t :: %__MODULE__{
          :password => String.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.Body21 do
  def decode(value, _options) do
    value
  end
end
