# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.Body16 do
  @moduledoc """
  Registrant Status
  """

  @derive [Poison.Encoder]
  defstruct [
    :action,
    :registrants
  ]

  @type t :: %__MODULE__{
          :action => String.t(),
          :registrants => [
            ZoomAPI.Model.MeetingsmeetingIdrecordingsregistrantsstatusRegistrants.t()
          ]
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.Body16 do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :registrants,
      :list,
      ZoomAPI.Model.MeetingsmeetingIdrecordingsregistrantsstatusRegistrants,
      options
    )
  end
end
