# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.Body35 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :calling_plans
  ]

  @type t :: %__MODULE__{
          :calling_plans => [PhoneusersuserIdcallingPlansCallingPlans]
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.Body35 do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :calling_plans,
      :list,
      ZoomAPI.Model.PhoneusersuserIdcallingPlansCallingPlans,
      options
    )
  end
end
