# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.Body20 do
  @moduledoc """
  The action.
  """

  @derive [Poison.Encoder]
  defstruct [
    :action
  ]

  @type t :: %__MODULE__{
          :action => String.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.Body20 do
  def decode(value, _options) do
    value
  end
end
