# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.Body19 do
  @moduledoc """
  The user update object represents a user on Zoom.
  """

  @derive [Poison.Encoder]
  defstruct [
    :first_name,
    :last_name,
    :type,
    :pmi,
    :use_pmi,
    :timezone,
    :language,
    :dept,
    :vanity_name,
    :host_key,
    :cms_user_id
  ]

  @type t :: %__MODULE__{
          :first_name => String.t(),
          :last_name => String.t(),
          :type => integer(),
          :pmi => integer(),
          :use_pmi => boolean(),
          :timezone => String.t(),
          :language => String.t(),
          :dept => String.t(),
          :vanity_name => String.t(),
          :host_key => String.t(),
          :cms_user_id => String.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.Body19 do
  def decode(value, _options) do
    value
  end
end
