# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.Body31 do
  @moduledoc """
  Meeting live stream status.
  """

  @derive [Poison.Encoder]
  defstruct [
    :action,
    :settings
  ]

  @type t :: %__MODULE__{
          :action => String.t(),
          :settings => MeetingsmeetingIdlivestreamstatusSettings
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.Body31 do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :settings,
      :struct,
      ZoomAPI.Model.MeetingsmeetingIdlivestreamstatusSettings,
      options
    )
  end
end
