# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.Body13 do
  @moduledoc """
  Registrant Status:&lt;br&gt;&#x60;approve&#x60; - Approve registrant.&lt;br&gt;&#x60;cancel&#x60; - Cancel registrant.&lt;br&gt;&#x60;deny&#x60; - Deny registrant.
  """

  @derive [Poison.Encoder]
  defstruct [
    :action,
    :registrants
  ]

  @type t :: %__MODULE__{
          :action => String.t(),
          :registrants => [MeetingsmeetingIdregistrantsstatusRegistrants]
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.Body13 do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :registrants,
      :list,
      ZoomAPI.Model.MeetingsmeetingIdregistrantsstatusRegistrants,
      options
    )
  end
end
