# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.Body8 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :members
  ]

  @type t :: %__MODULE__{
          :members => [ZoomAPI.Model.GroupsgroupIdmembersMembers.t()]
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.Body8 do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:members, :list, ZoomAPI.Model.GroupsgroupIdmembersMembers, options)
  end
end
