# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.Body34 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :phone_numbers
  ]

  @type t :: %__MODULE__{
          :phone_numbers => [PhoneusersuserIdphoneNumbersPhoneNumbers]
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.Body34 do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :phone_numbers,
      :list,
      ZoomAPI.Model.PhoneusersuserIdphoneNumbersPhoneNumbers,
      options
    )
  end
end
