# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.Body17 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :tsp_provider,
    :enable,
    :tsp_enabled,
    :master_account_setting_extended,
    :modify_credential_forbidden,
    :dial_in_number_unrestricted
  ]

  @type t :: %__MODULE__{
          :tsp_provider => String.t(),
          :enable => boolean(),
          :tsp_enabled => boolean(),
          :master_account_setting_extended => boolean(),
          :modify_credential_forbidden => boolean(),
          :dial_in_number_unrestricted => boolean()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.Body17 do
  def decode(value, _options) do
    value
  end
end
