# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.CustomQuestion do
  @moduledoc """
  Custom Question.
  """

  @derive [Poison.Encoder]
  defstruct [
    :title,
    :value
  ]

  @type t :: %__MODULE__{
          :title => String.t(),
          :value => String.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.CustomQuestion do
  def decode(value, _options) do
    value
  end
end
