# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.Device do
  @moduledoc """
  The H.323/SIP device object.
  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :protocol,
    :ip,
    :encryption
  ]

  @type t :: %__MODULE__{
          :name => String.t(),
          :protocol => String.t(),
          :ip => String.t(),
          :encryption => String.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.Device do
  def decode(value, _options) do
    value
  end
end
