# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.Group do
  @moduledoc """
  Group object.
  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :total_members
  ]

  @type t :: %__MODULE__{
          :name => String.t(),
          :total_members => integer()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.Group do
  def decode(value, _options) do
    value
  end
end
