# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse2006 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :members,
    :page_count,
    :page_number,
    :page_size,
    :total_records
  ]

  @type t :: %__MODULE__{
          :members => [InlineResponse2006Members],
          :page_count => integer(),
          :page_number => integer(),
          :page_size => integer(),
          :total_records => integer()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse2006 do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:members, :list, ZoomAPI.Model.InlineResponse2006Members, options)
  end
end
