# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse200 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :owner_id,
    :owner_email,
    :created_at,
    :options,
    :vanity_url
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :owner_id => String.t(),
          :owner_email => String.t(),
          :created_at => DateTime.t(),
          :options => AccountsOptions,
          :vanity_url => String.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse200 do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:options, :struct, ZoomAPI.Model.AccountsOptions, options)
  end
end
