# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse2007 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name,
    :total_members
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :name => String.t(),
          :total_members => integer()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse2007 do
  def decode(value, _options) do
    value
  end
end
