# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20036 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :tsp_accounts
  ]

  @type t :: %__MODULE__{
          :tsp_accounts => [TspAccountsList]
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20036 do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:tsp_accounts, :list, ZoomAPI.Model.TspAccountsList, options)
  end
end
