# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20025 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :uuid,
    :id,
    :type,
    :topic,
    :user_name,
    :user_email,
    :start_time,
    :end_time,
    :duration,
    :total_minutes,
    :participants_count,
    :tracking_fields
  ]

  @type t :: %__MODULE__{
          :uuid => String.t(),
          :id => integer(),
          :type => integer(),
          :topic => String.t(),
          :user_name => String.t(),
          :user_email => String.t(),
          :start_time => DateTime.t(),
          :end_time => DateTime.t(),
          :duration => integer(),
          :total_minutes => integer(),
          :participants_count => integer(),
          :tracking_fields => [InlineResponse20025TrackingFields]
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20025 do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :tracking_fields,
      :list,
      ZoomAPI.Model.InlineResponse20025TrackingFields,
      options
    )
  end
end
