# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20044 do
  @moduledoc """
  Phone User Setting
  """

  @derive [Poison.Encoder]
  defstruct [
    :outbound_caller,
    :area_code
  ]

  @type t :: %__MODULE__{
          :outbound_caller => InlineResponse20044OutboundCaller,
          :area_code => String.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20044 do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :outbound_caller,
      :struct,
      ZoomAPI.Model.InlineResponse20044OutboundCaller,
      options
    )
  end
end
