# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse2008 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :from,
    :next_page_token,
    :page_size,
    :sessions,
    :to
  ]

  @type t :: %__MODULE__{
          :from => Date.t(),
          :next_page_token => String.t(),
          :page_size => integer(),
          :sessions => [InlineResponse2008Sessions],
          :to => Date.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse2008 do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:from, :date, nil, options)
    |> deserialize(:sessions, :list, ZoomAPI.Model.InlineResponse2008Sessions, options)
    |> deserialize(:to, :date, nil, options)
  end
end
