# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20044OutboundCaller do
  @moduledoc """
  Outbound Caller Info
  """

  @derive [Poison.Encoder]
  defstruct [
    :number
  ]

  @type t :: %__MODULE__{
          :number => String.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20044OutboundCaller do
  def decode(value, _options) do
    value
  end
end
