# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20016 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :next_page_token,
    :page_count,
    :page_size,
    :participants,
    :total_records
  ]

  @type t :: %__MODULE__{
          :next_page_token => String.t(),
          :page_count => integer(),
          :page_size => integer(),
          :participants => [InlineResponse20016Participants],
          :total_records => integer()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20016 do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:participants, :list, ZoomAPI.Model.InlineResponse20016Participants, options)
  end
end
