# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20041 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :client_feedback_details,
    :from,
    :next_page_token,
    :page_size,
    :to
  ]

  @type t :: %__MODULE__{
          :client_feedback_details => [InlineResponse20041ClientFeedbackDetails],
          :from => Date.t(),
          :next_page_token => String.t(),
          :page_size => integer(),
          :to => Date.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20041 do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :client_feedback_details,
      :list,
      ZoomAPI.Model.InlineResponse20041ClientFeedbackDetails,
      options
    )
    |> deserialize(:from, :date, nil, options)
    |> deserialize(:to, :date, nil, options)
  end
end
