# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20042Messages do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :message,
    :sender,
    :date_time,
    :timstamp
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :message => String.t(),
          :sender => String.t(),
          :date_time => DateTime.t(),
          :timstamp => integer()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20042Messages do
  def decode(value, _options) do
    value
  end
end
