# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20110 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :ids,
    :add_at
  ]

  @type t :: %__MODULE__{
          :ids => String.t(),
          :add_at => DateTime.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20110 do
  def decode(value, _options) do
    value
  end
end
