# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20040 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :custom_questions,
    :questions
  ]

  @type t :: %__MODULE__{
          :custom_questions => [InlineResponse20040CustomQuestions],
          :questions => [InlineResponse20040Questions]
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20040 do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :custom_questions,
      :list,
      ZoomAPI.Model.InlineResponse20040CustomQuestions,
      options
    )
    |> deserialize(:questions, :list, ZoomAPI.Model.InlineResponse20040Questions, options)
  end
end
