# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse2013 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :field,
    :recommended_values,
    :required,
    :visible
  ]

  @type t :: %__MODULE__{
          :field => String.t(),
          :recommended_values => [String.t()],
          :required => boolean(),
          :visible => boolean()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse2013 do
  def decode(value, _options) do
    value
  end
end
