# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20017Participants do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :user_id,
    :user_name,
    :details
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :user_id => String.t(),
          :user_name => String.t(),
          :details => [InlineResponse20017Details]
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20017Participants do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:details, :list, ZoomAPI.Model.InlineResponse20017Details, options)
  end
end
