# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse2017 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :questions,
    :status,
    :title
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :questions => [InlineResponse2017Questions],
          :status => String.t(),
          :title => String.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse2017 do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:questions, :list, ZoomAPI.Model.InlineResponse2017Questions, options)
  end
end
