# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20050 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :calls
  ]

  @type t :: %__MODULE__{
          :calls => [InlineResponse20050Calls]
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20050 do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:calls, :list, ZoomAPI.Model.InlineResponse20050Calls, options)
  end
end
