# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse201 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :owner_id,
    :owner_email,
    :created_at
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :owner_id => String.t(),
          :owner_email => String.t(),
          :created_at => String.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse201 do
  def decode(value, _options) do
    value
  end
end
