# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20029 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :uuid,
    :start_time,
    :questions
  ]

  @type t :: %__MODULE__{
          :id => integer(),
          :uuid => String.t(),
          :start_time => DateTime.t(),
          :questions => [InlineResponse20027Questions]
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20029 do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:questions, :list, ZoomAPI.Model.InlineResponse20027Questions, options)
  end
end
