# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20041ClientFeedbackDetails do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :participant_name,
    :meeting_id,
    :time,
    :email
  ]

  @type t :: %__MODULE__{
          :participant_name => String.t(),
          :meeting_id => String.t(),
          :time => DateTime.t(),
          :email => String.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20041ClientFeedbackDetails do
  def decode(value, _options) do
    value
  end
end
