# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse2015Occurrences do
  @moduledoc """
  Occurence object.
  """

  @derive [Poison.Encoder]
  defstruct [
    :occurrence_id,
    :start_time,
    :duration,
    :status
  ]

  @type t :: %__MODULE__{
          :occurrence_id => integer(),
          :start_time => DateTime.t(),
          :duration => integer(),
          :status => String.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse2015Occurrences do
  def decode(value, _options) do
    value
  end
end
