# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20023Users do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :email,
    :user_name,
    :type,
    :dept,
    :meetings,
    :participants,
    :meeting_minutes
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :email => String.t(),
          :user_name => String.t(),
          :type => integer(),
          :dept => String.t(),
          :meetings => integer(),
          :participants => integer(),
          :meeting_minutes => integer()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20023Users do
  def decode(value, _options) do
    value
  end
end
