# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20040CustomQuestions do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :title,
    :type,
    :required,
    :answers
  ]

  @type t :: %__MODULE__{
          :title => String.t(),
          :type => String.t(),
          :required => boolean(),
          :answers => [String.t()]
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20040CustomQuestions do
  def decode(value, _options) do
    value
  end
end
