# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20053Recording do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :local_recording,
    :cloud_recording,
    :auto_recording,
    :cloud_recording_download,
    :account_user_access_recording,
    :host_delete_cloud_recording,
    :auto_delete_cmr
  ]

  @type t :: %__MODULE__{
          :local_recording => boolean(),
          :cloud_recording => boolean(),
          :auto_recording => String.t(),
          :cloud_recording_download => boolean(),
          :account_user_access_recording => boolean(),
          :host_delete_cloud_recording => boolean(),
          :auto_delete_cmr => boolean()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20053Recording do
  def decode(value, _options) do
    value
  end
end
