# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20031 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :next_page_token,
    :page_size
  ]

  @type t :: %__MODULE__{
          :next_page_token => String.t(),
          :page_size => integer()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20031 do
  def decode(value, _options) do
    value
  end
end
