# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse2006Members do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :email,
    :first_name,
    :id,
    :last_name,
    :type
  ]

  @type t :: %__MODULE__{
          :email => String.t(),
          :first_name => String.t(),
          :id => String.t(),
          :last_name => String.t(),
          :type => integer()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse2006Members do
  def decode(value, _options) do
    value
  end
end
