# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20011 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :uuid,
    :id,
    :host_id,
    :type,
    :topic,
    :user_name,
    :user_email,
    :start_time,
    :end_time,
    :duration,
    :total_minutes,
    :participants_count
  ]

  @type t :: %__MODULE__{
          :uuid => String.t(),
          :id => integer(),
          :host_id => integer(),
          :type => integer(),
          :topic => String.t(),
          :user_name => String.t(),
          :user_email => String.t(),
          :start_time => DateTime.t(),
          :end_time => DateTime.t(),
          :duration => integer(),
          :total_minutes => integer(),
          :participants_count => integer()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20011 do
  def decode(value, _options) do
    value
  end
end
