# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20115 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :auth_password,
    :auth_user,
    :created_at,
    :events,
    :url,
    :webhook_id
  ]

  @type t :: %__MODULE__{
          :auth_password => String.t(),
          :auth_user => String.t(),
          :created_at => DateTime.t(),
          :events => [String.t()],
          :url => String.t(),
          :webhook_id => String.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20115 do
  def decode(value, _options) do
    value
  end
end
