# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse2018 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :registrant_id,
    :id,
    :topic,
    :share_url
  ]

  @type t :: %__MODULE__{
          :registrant_id => String.t(),
          :id => String.t(),
          :topic => String.t(),
          :share_url => String.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse2018 do
  def decode(value, _options) do
    value
  end
end
