# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20014Questions do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :field_name,
    :required
  ]

  @type t :: %__MODULE__{
          :field_name => String.t(),
          :required => boolean()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20014Questions do
  def decode(value, _options) do
    value
  end
end
