# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20022IssueDetails do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :issue,
    :time
  ]

  @type t :: %__MODULE__{
          :issue => String.t(),
          :time => DateTime.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20022IssueDetails do
  def decode(value, _options) do
    value
  end
end
