# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20052InMeeting do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :e2e_encryption,
    :chat,
    :private_chat,
    :auto_saving_chat,
    :entry_exit_chime,
    :record_play_own_voice,
    :file_transfer,
    :feedback,
    :post_meeting_feedback,
    :co_host,
    :polling,
    :attendee_on_hold,
    :show_meeting_control_toolbar,
    :allow_show_zoom_windows,
    :annotation,
    :whiteboard,
    :remote_control,
    :non_verbal_feedback,
    :breakout_room,
    :remote_support,
    :closed_caption,
    :far_end_camera_control,
    :group_hd,
    :virtual_background,
    :alert_guest_join,
    :auto_answer,
    :sending_default_email_invites,
    :use_html_format_email,
    :stereo_audio,
    :original_audio,
    :show_device_list,
    :only_host_view_device_list,
    :screen_sharing,
    :attention_tracking,
    :waiting_room,
    :show_browser_join_link
  ]

  @type t :: %__MODULE__{
          :e2e_encryption => boolean(),
          :chat => boolean(),
          :private_chat => boolean(),
          :auto_saving_chat => boolean(),
          :entry_exit_chime => String.t(),
          :record_play_own_voice => boolean(),
          :file_transfer => boolean(),
          :feedback => boolean(),
          :post_meeting_feedback => boolean(),
          :co_host => boolean(),
          :polling => boolean(),
          :attendee_on_hold => boolean(),
          :show_meeting_control_toolbar => boolean(),
          :allow_show_zoom_windows => boolean(),
          :annotation => boolean(),
          :whiteboard => boolean(),
          :remote_control => boolean(),
          :non_verbal_feedback => boolean(),
          :breakout_room => boolean(),
          :remote_support => boolean(),
          :closed_caption => boolean(),
          :far_end_camera_control => boolean(),
          :group_hd => boolean(),
          :virtual_background => boolean(),
          :alert_guest_join => boolean(),
          :auto_answer => boolean(),
          :sending_default_email_invites => boolean(),
          :use_html_format_email => boolean(),
          :stereo_audio => boolean(),
          :original_audio => boolean(),
          :show_device_list => boolean(),
          :only_host_view_device_list => boolean(),
          :screen_sharing => boolean(),
          :attention_tracking => boolean(),
          :waiting_room => boolean(),
          :show_browser_join_link => boolean()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20052InMeeting do
  def decode(value, _options) do
    value
  end
end
