# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20034 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :account_id,
    :cms_user_id,
    :created_at,
    :dept,
    :email,
    :first_name,
    :group_ids,
    :host_key,
    :id,
    :im_group_ids,
    :jid,
    :language,
    :last_client_version,
    :last_login_time,
    :last_name,
    :personal_meeting_url,
    :phone_country,
    :phone_number,
    :pic_url,
    :pmi,
    :status,
    :timezone,
    :type,
    :use_pmi,
    :vanity_url,
    :verified
  ]

  @type t :: %__MODULE__{
          :account_id => String.t(),
          :cms_user_id => String.t(),
          :created_at => DateTime.t(),
          :dept => String.t(),
          :email => String.t(),
          :first_name => String.t(),
          :group_ids => [String.t()],
          :host_key => String.t(),
          :id => String.t(),
          :im_group_ids => [String.t()],
          :jid => String.t(),
          :language => String.t(),
          :last_client_version => String.t(),
          :last_login_time => DateTime.t(),
          :last_name => String.t(),
          :personal_meeting_url => String.t(),
          :phone_country => String.t(),
          :phone_number => String.t(),
          :pic_url => String.t(),
          :pmi => integer(),
          :status => String.t(),
          :timezone => String.t(),
          :type => integer(),
          :use_pmi => boolean(),
          :vanity_url => String.t(),
          :verified => integer()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20034 do
  def decode(value, _options) do
    value
  end
end
