# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20042 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :date,
    :messages,
    :next_page_token,
    :page_size
  ]

  @type t :: %__MODULE__{
          :date => DateTime.t(),
          :messages => [InlineResponse20042Messages],
          :next_page_token => String.t(),
          :page_size => integer()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20042 do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:messages, :list, ZoomAPI.Model.InlineResponse20042Messages, options)
  end
end
