# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse2009 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :from,
    :messages,
    :next_page_token,
    :page_size,
    :session_id,
    :to
  ]

  @type t :: %__MODULE__{
          :from => Date.t(),
          :messages => [InlineResponse2009Messages],
          :next_page_token => String.t(),
          :page_size => integer(),
          :session_id => String.t(),
          :to => Date.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse2009 do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:from, :date, nil, options)
    |> deserialize(:messages, :list, ZoomAPI.Model.InlineResponse2009Messages, options)
    |> deserialize(:to, :date, nil, options)
  end
end
