# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20051 do
  @moduledoc """
  Report object
  """

  @derive [Poison.Encoder]
  defstruct [
    :from,
    :to,
    :page_size,
    :next_page_token,
    :activity_logs
  ]

  @type t :: %__MODULE__{
          :from => String.t(),
          :to => String.t(),
          :page_size => String.t(),
          :next_page_token => String.t(),
          :activity_logs => [InlineResponse20051ActivityLogs]
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20051 do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:activity_logs, :list, ZoomAPI.Model.InlineResponse20051ActivityLogs, options)
  end
end
