# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20047 do
  @moduledoc """
  Phone User Voice Mails
  """

  @derive [Poison.Encoder]
  defstruct [
    :page_count,
    :page_number,
    :page_size,
    :total_records,
    :voice_mails
  ]

  @type t :: %__MODULE__{
          :page_count => String.t(),
          :page_number => String.t(),
          :page_size => String.t(),
          :total_records => String.t(),
          :voice_mails => [InlineResponse20047VoiceMails]
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20047 do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:voice_mails, :list, ZoomAPI.Model.InlineResponse20047VoiceMails, options)
  end
end
