# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse2012 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :encryption,
    :id,
    :ip,
    :name,
    :protocol
  ]

  @type t :: %__MODULE__{
          :encryption => String.t(),
          :id => String.t(),
          :ip => String.t(),
          :name => String.t(),
          :protocol => String.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse2012 do
  def decode(value, _options) do
    value
  end
end
