# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20021Users do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :user_id,
    :user_name,
    :email,
    :total_send,
    :total_receive,
    :group_send,
    :group_receive,
    :calls_send,
    :calls_receive,
    :files_send,
    :files_receive,
    :images_send,
    :images_receive,
    :voice_send,
    :voice_receive,
    :videos_send,
    :videos_receive,
    :emoji_send,
    :emoji_receive
  ]

  @type t :: %__MODULE__{
          :user_id => String.t(),
          :user_name => String.t(),
          :email => String.t(),
          :total_send => integer(),
          :total_receive => integer(),
          :group_send => integer(),
          :group_receive => integer(),
          :calls_send => integer(),
          :calls_receive => integer(),
          :files_send => integer(),
          :files_receive => integer(),
          :images_send => integer(),
          :images_receive => integer(),
          :voice_send => integer(),
          :voice_receive => integer(),
          :videos_send => integer(),
          :videos_receive => integer(),
          :emoji_send => integer(),
          :emoji_receive => integer()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20021Users do
  def decode(value, _options) do
    value
  end
end
