# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20052ScheduleMeeting do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :host_video,
    :participant_video,
    :audio_type,
    :join_before_host,
    :require_password_for_all_meetings,
    :force_pmi_jbh_password,
    :pstn_password_protected,
    :mute_upon_entry,
    :upcoming_meeting_reminder
  ]

  @type t :: %__MODULE__{
          :host_video => boolean(),
          :participant_video => boolean(),
          :audio_type => String.t(),
          :join_before_host => boolean(),
          :require_password_for_all_meetings => boolean(),
          :force_pmi_jbh_password => boolean(),
          :pstn_password_protected => boolean(),
          :mute_upon_entry => boolean(),
          :upcoming_meeting_reminder => boolean()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20052ScheduleMeeting do
  def decode(value, _options) do
    value
  end
end
