# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse2003PlanAudio do
  @moduledoc """
  Additional audio conferencing &lt;a href&#x3D;\&quot;/api-reference/other-references/plans\&quot;&gt;plan type.&lt;/a&gt;
  """

  @derive [Poison.Encoder]
  defstruct [
    :type,
    :tollfree_countries,
    :premium_countries,
    :callout_countries,
    :ddi_numbers
  ]

  @type t :: %__MODULE__{
          :type => String.t(),
          :tollfree_countries => String.t(),
          :premium_countries => String.t(),
          :callout_countries => String.t(),
          :ddi_numbers => integer()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse2003PlanAudio do
  def decode(value, _options) do
    value
  end
end
