# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20028Participants do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :user_id,
    :name,
    :user_email,
    :join_time,
    :leave_time,
    :duration,
    :attentiveness_score
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :user_id => String.t(),
          :name => String.t(),
          :user_email => String.t(),
          :join_time => DateTime.t(),
          :leave_time => DateTime.t(),
          :duration => integer(),
          :attentiveness_score => String.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20028Participants do
  def decode(value, _options) do
    value
  end
end
