# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse2004 do
  @moduledoc """
  List of Groups.
  """

  @derive [Poison.Encoder]
  defstruct [
    :total_records,
    :groups
  ]

  @type t :: %__MODULE__{
          :total_records => integer(),
          :groups => [Object]
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse2004 do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:groups, :list, ZoomAPI.Model.Object, options)
  end
end
