# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20033Users do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :first_name,
    :last_name,
    :email,
    :type,
    :pmi,
    :timezone,
    :dept,
    :created_at,
    :last_login_time,
    :last_client_version,
    :group_ids,
    :im_group_ids,
    :verified
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :first_name => String.t(),
          :last_name => String.t(),
          :email => String.t(),
          :type => integer(),
          :pmi => integer(),
          :timezone => String.t(),
          :dept => String.t(),
          :created_at => DateTime.t(),
          :last_login_time => DateTime.t(),
          :last_client_version => String.t(),
          :group_ids => [String.t()],
          :im_group_ids => [String.t()],
          :verified => integer()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20033Users do
  def decode(value, _options) do
    value
  end
end
