# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20020 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :account_type,
    :calender_name,
    :camera,
    :device_ip,
    :email,
    :id,
    :last_start_time,
    :live_meeting,
    :location,
    :microphone,
    :past_meetings,
    :room_name,
    :speaker,
    :status
  ]

  @type t :: %__MODULE__{
          :account_type => String.t(),
          :calender_name => String.t(),
          :camera => String.t(),
          :device_ip => String.t(),
          :email => String.t(),
          :id => String.t(),
          :last_start_time => String.t(),
          :live_meeting => MeetingMetrics,
          :location => String.t(),
          :microphone => String.t(),
          :past_meetings => Object,
          :room_name => String.t(),
          :speaker => String.t(),
          :status => String.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20020 do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:live_meeting, :struct, ZoomAPI.Model.MeetingMetrics, options)
    |> deserialize(:past_meetings, :struct, ZoomAPI.Model.Object, options)
  end
end
