# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20045CallLogs do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :caller_number,
    :caller_number_type,
    :caller_name,
    :callee_number,
    :callee_number_type,
    :callee_name,
    :direction,
    :duration,
    :result,
    :date_time
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :caller_number => String.t(),
          :caller_number_type => String.t(),
          :caller_name => String.t(),
          :callee_number => String.t(),
          :callee_number_type => String.t(),
          :callee_name => String.t(),
          :direction => String.t(),
          :duration => integer(),
          :result => String.t(),
          :date_time => String.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20045CallLogs do
  def decode(value, _options) do
    value
  end
end
