# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20043 do
  @moduledoc """
  Zoom User Profile
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :phone_user_id,
    :email,
    :calling_plan,
    :phone_numbers,
    :extension_number
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :phone_user_id => String.t(),
          :email => String.t(),
          :calling_plan => [InlineResponse20043CallingPlan],
          :phone_numbers => [InlineResponse20043PhoneNumbers],
          :extension_number => integer()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20043 do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:calling_plan, :list, ZoomAPI.Model.InlineResponse20043CallingPlan, options)
    |> deserialize(:phone_numbers, :list, ZoomAPI.Model.InlineResponse20043PhoneNumbers, options)
  end
end
