# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse2008Sessions do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :session_id,
    :type,
    :name,
    :last_message_sent_time
  ]

  @type t :: %__MODULE__{
          :session_id => String.t(),
          :type => String.t(),
          :name => String.t(),
          :last_message_sent_time => DateTime.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse2008Sessions do
  def decode(value, _options) do
    value
  end
end
