# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20050Calls do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :extension_id,
    :direction,
    :status,
    :caller_number,
    :callee_number,
    :caller_extension_number,
    :callee_extension_number,
    :ringing_start_time,
    :answer_start_time,
    :call_end_time,
    :time
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :extension_id => String.t(),
          :direction => String.t(),
          :status => String.t(),
          :caller_number => String.t(),
          :callee_number => String.t(),
          :caller_extension_number => String.t(),
          :callee_extension_number => String.t(),
          :ringing_start_time => String.t(),
          :answer_start_time => String.t(),
          :call_end_time => String.t(),
          :time => String.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20050Calls do
  def decode(value, _options) do
    value
  end
end
