# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20023 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :from,
    :page_count,
    :page_number,
    :page_size,
    :to,
    :total_meeting_minutes,
    :total_meetings,
    :total_participants,
    :total_records,
    :users
  ]

  @type t :: %__MODULE__{
          :from => Date.t(),
          :page_count => integer(),
          :page_number => integer(),
          :page_size => integer(),
          :to => Date.t(),
          :total_meeting_minutes => integer(),
          :total_meetings => integer(),
          :total_participants => integer(),
          :total_records => integer(),
          :users => [InlineResponse20023Users]
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20023 do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:from, :date, nil, options)
    |> deserialize(:to, :date, nil, options)
    |> deserialize(:users, :list, ZoomAPI.Model.InlineResponse20023Users, options)
  end
end
