# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20036DialInNumbers do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :code,
    :number,
    :type,
    :country_label
  ]

  @type t :: %__MODULE__{
          :code => String.t(),
          :number => String.t(),
          :type => String.t(),
          :country_label => String.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20036DialInNumbers do
  def decode(value, _options) do
    value
  end
end
