# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20027Questions do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :email,
    :question_details
  ]

  @type t :: %__MODULE__{
          :name => String.t(),
          :email => String.t(),
          :question_details => [InlineResponse20027QuestionDetails]
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20027Questions do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :question_details,
      :list,
      ZoomAPI.Model.InlineResponse20027QuestionDetails,
      options
    )
  end
end
