# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.InlineResponse20017Details do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :content,
    :start_time,
    :end_time
  ]

  @type t :: %__MODULE__{
          :content => String.t(),
          :start_time => String.t(),
          :end_time => String.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.InlineResponse20017Details do
  def decode(value, _options) do
    value
  end
end
