# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.MeetingRecordingRegistrantList do
  @moduledoc """
  List of meeting recording registrant
  """

  @derive [Poison.Encoder]
  defstruct []

  @type t :: %__MODULE__{}
end

defimpl Poison.Decoder, for: ZoomAPI.Model.MeetingRecordingRegistrantList do
  def decode(value, _options) do
    value
  end
end
