# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.MeetingRegistrantQuestions do
  @moduledoc """
  Meeting Registrant Questions
  """

  @derive [Poison.Encoder]
  defstruct [
    :questions,
    :custom_questions
  ]

  @type t :: %__MODULE__{
          :questions => [InlineResponse20013Questions],
          :custom_questions => [InlineResponse20013CustomQuestions]
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.MeetingRegistrantQuestions do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:questions, :list, ZoomAPI.Model.InlineResponse20013Questions, options)
    |> deserialize(
      :custom_questions,
      :list,
      ZoomAPI.Model.InlineResponse20013CustomQuestions,
      options
    )
  end
end
