# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.MeetingList do
  @moduledoc """
  List of meetings.
  """

  @derive [Poison.Encoder]
  defstruct [
    :meetings
  ]

  @type t :: %__MODULE__{
          :meetings => [Object]
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.MeetingList do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:meetings, :list, ZoomAPI.Model.Object, options)
  end
end
