# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.MeetingInvitation do
  @moduledoc """
  Meeting invitation details.
  """

  @derive [Poison.Encoder]
  defstruct [
    :invitation
  ]

  @type t :: %__MODULE__{
          :invitation => String.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.MeetingInvitation do
  def decode(value, _options) do
    value
  end
end
