# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.Pac do
  @moduledoc """
  List of PAC accounts.
  """

  @derive [Poison.Encoder]
  defstruct [
    :dedicated_dial_in_number,
    :global_dial_in_numbers,
    :conference_id,
    :participant_password,
    :listen_only_password
  ]

  @type t :: %__MODULE__{
          :dedicated_dial_in_number => [PacDedicatedDialInNumber],
          :global_dial_in_numbers => [PacDedicatedDialInNumber],
          :conference_id => integer(),
          :participant_password => String.t(),
          :listen_only_password => String.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.Pac do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :dedicated_dial_in_number,
      :list,
      ZoomAPI.Model.PacDedicatedDialInNumber,
      options
    )
    |> deserialize(
      :global_dial_in_numbers,
      :list,
      ZoomAPI.Model.PacDedicatedDialInNumber,
      options
    )
  end
end
