# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.PaginationToken4Qos do
  @moduledoc """
  Pagination object.
  """

  @derive [Poison.Encoder]
  defstruct [
    :page_count,
    :page_size,
    :total_records,
    :next_page_token
  ]

  @type t :: %__MODULE__{
          :page_count => integer(),
          :page_size => integer(),
          :total_records => integer(),
          :next_page_token => String.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.PaginationToken4Qos do
  def decode(value, _options) do
    value
  end
end
