# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.Panelist do
  @moduledoc """
  Panelist base object.
  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :email
  ]

  @type t :: %__MODULE__{
          :name => String.t(),
          :email => String.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.Panelist do
  def decode(value, _options) do
    value
  end
end
