# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.ParticipantQosList do
  @moduledoc """
  Participant QOS list.
  """

  @derive [Poison.Encoder]
  defstruct [
    :next_page_token,
    :page_count,
    :page_size,
    :total_records
  ]

  @type t :: %__MODULE__{
          :next_page_token => String.t(),
          :page_count => integer(),
          :page_size => integer(),
          :total_records => integer()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.ParticipantQosList do
  def decode(value, _options) do
    value
  end
end
