# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.ParticipantQosUserQos do
  @moduledoc """
  User quality of service.
  """

  @derive [Poison.Encoder]
  defstruct [
    :date_time,
    :audio_input,
    :audio_output,
    :video_input,
    :video_output,
    :as_input,
    :as_output,
    :cpu_usage
  ]

  @type t :: %__MODULE__{
          :date_time => DateTime.t(),
          :audio_input => QosObject,
          :audio_output => QosObject,
          :video_input => Object,
          :video_output => Object,
          :as_input => Object,
          :as_output => Object,
          :cpu_usage => ParticipantQosUserQosCpuUsage
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.ParticipantQosUserQos do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:audio_input, :struct, ZoomAPI.Model.QosObject, options)
    |> deserialize(:audio_output, :struct, ZoomAPI.Model.QosObject, options)
    |> deserialize(:video_input, :struct, :map, options)
    |> deserialize(:video_output, :struct, :map, options)
    |> deserialize(:as_input, :struct, :map, options)
    |> deserialize(:as_output, :struct, :map, options)
    |> deserialize(:cpu_usage, :struct, ZoomAPI.Model.ParticipantQosUserQosCpuUsage, options)
  end
end
