# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.Poll do
  @moduledoc """
  Poll
  """

  @derive [Poison.Encoder]
  defstruct [
    :title,
    :questions
  ]

  @type t :: %__MODULE__{
          :title => String.t(),
          :questions => [InlineResponse2017Questions]
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.Poll do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:questions, :list, ZoomAPI.Model.InlineResponse2017Questions, options)
  end
end
