# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.QosVideo do
  @moduledoc """
  Quality of service object.
  """

  @derive [Poison.Encoder]
  defstruct [
    :resolution,
    :frame_rate
  ]

  @type t :: %__MODULE__{
          :resolution => String.t(),
          :frame_rate => String.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.QosVideo do
  def decode(value, _options) do
    value
  end
end
