# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.QosParticipantList do
  @moduledoc """
  Participant QOS list.
  """

  @derive [Poison.Encoder]
  defstruct [
    :participants
  ]

  @type t :: %__MODULE__{
          :participants => [ParticipantQos]
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.QosParticipantList do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:participants, :list, ZoomAPI.Model.ParticipantQos, options)
  end
end
