# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.QosParticipant do
  @moduledoc """
  Participant QOS.
  """

  @derive [Poison.Encoder]
  defstruct [
    :user_id,
    :user_name,
    :device,
    :ip_address,
    :location,
    :join_time,
    :leave_time,
    :pc_name,
    :domain,
    :mac_addr,
    :harddisk_id,
    :version,
    :user_qos
  ]

  @type t :: %__MODULE__{
          :user_id => String.t(),
          :user_name => String.t(),
          :device => String.t(),
          :ip_address => String.t(),
          :location => String.t(),
          :join_time => DateTime.t(),
          :leave_time => DateTime.t(),
          :pc_name => String.t(),
          :domain => String.t(),
          :mac_addr => String.t(),
          :harddisk_id => String.t(),
          :version => String.t(),
          :user_qos => ParticipantQosUserQos
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.QosParticipant do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:user_qos, :struct, ZoomAPI.Model.ParticipantQosUserQos, options)
  end
end
