# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.QosAudio do
  @moduledoc """
  Quality of Service object.
  """

  @derive [Poison.Encoder]
  defstruct [
    :bitrate,
    :latency,
    :jitter,
    :avg_loss,
    :max_loss
  ]

  @type t :: %__MODULE__{
          :bitrate => String.t(),
          :latency => String.t(),
          :jitter => String.t(),
          :avg_loss => String.t(),
          :max_loss => String.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.QosAudio do
  def decode(value, _options) do
    value
  end
end
