# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.RecordingSettings1 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :share_recording,
    :viewer_download,
    :password,
    :on_demand,
    :approval_type,
    :send_email_to_host,
    :show_social_share_buttons
  ]

  @type t :: %__MODULE__{
          :share_recording => String.t(),
          :viewer_download => boolean(),
          :password => String.t(),
          :on_demand => boolean(),
          :approval_type => integer(),
          :send_email_to_host => boolean(),
          :show_social_share_buttons => boolean()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.RecordingSettings1 do
  def decode(value, _options) do
    value
  end
end
