# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.RecordingRegistrantList do
  @moduledoc """
  List of Recording Registration
  """

  @derive [Poison.Encoder]
  defstruct [
    :registrants
  ]

  @type t :: %__MODULE__{
          :registrants => [map]
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.RecordingRegistrantList do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:registrants, :list, :map, options)
  end
end
