# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.Recurrence do
  @moduledoc """
  Recurrence object.
  """

  @derive [Poison.Encoder]
  defstruct [
    :type,
    :repeat_interval,
    :weekly_days,
    :monthly_day,
    :monthly_week,
    :monthly_week_day,
    :end_times,
    :end_date_time
  ]

  @type t :: %__MODULE__{
          :type => integer(),
          :repeat_interval => integer(),
          :weekly_days => integer(),
          :monthly_day => integer(),
          :monthly_week => integer(),
          :monthly_week_day => integer(),
          :end_times => integer(),
          :end_date_time => DateTime.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.Recurrence do
  def decode(value, _options) do
    value
  end
end
