# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.TrackingField do
  @moduledoc """
  Tracking Field
  """

  @derive [Poison.Encoder]
  defstruct [
    :field,
    :required,
    :visible,
    :recommended_values
  ]

  @type t :: %__MODULE__{
          :field => String.t(),
          :required => boolean(),
          :visible => boolean(),
          :recommended_values => [String.t()]
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.TrackingField do
  def decode(value, _options) do
    value
  end
end
