# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.UsersUserInfo do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :email,
    :type,
    :first_name,
    :last_name,
    :password
  ]

  @type t :: %__MODULE__{
          :email => String.t(),
          :type => integer(),
          :first_name => String.t(),
          :last_name => String.t(),
          :password => String.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.UsersUserInfo do
  def decode(value, _options) do
    value
  end
end
