# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.UserAssistantsList do
  @moduledoc """
  List of user&#39;s assistants.
  """

  @derive [Poison.Encoder]
  defstruct [
    :assistants
  ]

  @type t :: %__MODULE__{
          :assistants => [UserAssistantsListAssistants]
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.UserAssistantsList do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:assistants, :list, ZoomAPI.Model.UserAssistantsListAssistants, options)
  end
end
