# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.UserSettingsMeetingSettings do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :host_video,
    :participants_video,
    :audio_type,
    :join_before_host,
    :force_pmi_jbh_password,
    :pstn_password_protected,
    :use_pmi_for_scheduled_meetings,
    :use_pmi_for_instant_meetings
  ]

  @type t :: %__MODULE__{
          :host_video => boolean(),
          :participants_video => boolean(),
          :audio_type => String.t(),
          :join_before_host => boolean(),
          :force_pmi_jbh_password => boolean(),
          :pstn_password_protected => boolean(),
          :use_pmi_for_scheduled_meetings => boolean(),
          :use_pmi_for_instant_meetings => boolean()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.UserSettingsMeetingSettings do
  def decode(value, _options) do
    value
  end
end
