# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.UserSettingsMeetingSettings1 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :e2e_encryption,
    :chat,
    :private_chat,
    :auto_saving_chat,
    :entry_exit_chime,
    :record_play_voice,
    :file_transfer,
    :feedback,
    :co_host,
    :polling,
    :attendee_on_hold,
    :annotation,
    :remote_control,
    :non_verbal_feedback,
    :breakout_room,
    :remote_support,
    :closed_caption,
    :group_hd,
    :virtual_background,
    :far_end_camera_control,
    :share_dual_camera,
    :attention_tracking,
    :waiting_room,
    :allow_live_streaming,
    :workplace_by_facebook,
    :custom_live_streaming,
    :custom_service_instructions
  ]

  @type t :: %__MODULE__{
          :e2e_encryption => boolean(),
          :chat => boolean(),
          :private_chat => boolean(),
          :auto_saving_chat => boolean(),
          :entry_exit_chime => String.t(),
          :record_play_voice => boolean(),
          :file_transfer => boolean(),
          :feedback => boolean(),
          :co_host => boolean(),
          :polling => boolean(),
          :attendee_on_hold => boolean(),
          :annotation => boolean(),
          :remote_control => boolean(),
          :non_verbal_feedback => boolean(),
          :breakout_room => boolean(),
          :remote_support => boolean(),
          :closed_caption => boolean(),
          :group_hd => boolean(),
          :virtual_background => boolean(),
          :far_end_camera_control => boolean(),
          :share_dual_camera => boolean(),
          :attention_tracking => boolean(),
          :waiting_room => boolean(),
          :allow_live_streaming => boolean(),
          :workplace_by_facebook => boolean(),
          :custom_live_streaming => boolean(),
          :custom_service_instructions => String.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.UserSettingsMeetingSettings1 do
  def decode(value, _options) do
    value
  end
end
