# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.User do
  @moduledoc """
  The user object represents a specific user on Zoom.
  """

  @derive [Poison.Encoder]
  defstruct [
    :first_name,
    :last_name,
    :email,
    :type,
    :pmi,
    :use_pmi,
    :timezone,
    :dept,
    :created_at,
    :last_login_time,
    :last_client_version
  ]

  @type t :: %__MODULE__{
          :first_name => String.t(),
          :last_name => String.t(),
          :email => String.t(),
          :type => integer(),
          :pmi => integer(),
          :use_pmi => boolean(),
          :timezone => String.t(),
          :dept => String.t(),
          :created_at => DateTime.t(),
          :last_login_time => DateTime.t(),
          :last_client_version => String.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.User do
  def decode(value, _options) do
    value
  end
end
