# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.UserSettingsFeatureSettings1 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :meeting_capacity,
    :large_meeting,
    :large_meeting_capacity,
    :webinar,
    :webinar_capacity
  ]

  @type t :: %__MODULE__{
          :meeting_capacity => integer(),
          :large_meeting => boolean(),
          :large_meeting_capacity => integer(),
          :webinar => boolean(),
          :webinar_capacity => integer()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.UserSettingsFeatureSettings1 do
  def decode(value, _options) do
    value
  end
end
