# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.UserSettings do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :schedule_meeting,
    :in_meeting,
    :email_notification,
    :recording,
    :telephony,
    :feature,
    :tsp
  ]

  @type t :: %__MODULE__{
          :schedule_meeting => UserSettingsMeetingSettings,
          :in_meeting => UserSettingsMeetingSettings1,
          :email_notification => UserSettingsNotificationSettings,
          :recording => UserSettingsRecordingSettings,
          :telephony => UserSettingsMeetingSettings2,
          :feature => UserSettingsFeatureSettings,
          :tsp => UserSettingsTspSettings
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.UserSettings do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:schedule_meeting, :struct, ZoomAPI.Model.UserSettingsMeetingSettings, options)
    |> deserialize(:in_meeting, :struct, ZoomAPI.Model.UserSettingsMeetingSettings1, options)
    |> deserialize(
      :email_notification,
      :struct,
      ZoomAPI.Model.UserSettingsNotificationSettings,
      options
    )
    |> deserialize(:recording, :struct, ZoomAPI.Model.UserSettingsRecordingSettings, options)
    |> deserialize(:telephony, :struct, ZoomAPI.Model.UserSettingsMeetingSettings2, options)
    |> deserialize(:feature, :struct, ZoomAPI.Model.UserSettingsFeatureSettings, options)
    |> deserialize(:tsp, :struct, ZoomAPI.Model.UserSettingsTspSettings, options)
  end
end
