# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.UserSettingsTelephony do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :third_party_audio,
    :audio_conference_info,
    :show_international_numbers_link
  ]

  @type t :: %__MODULE__{
          :third_party_audio => boolean(),
          :audio_conference_info => String.t(),
          :show_international_numbers_link => boolean()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.UserSettingsTelephony do
  def decode(value, _options) do
    value
  end
end
