# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.Webhook do
  @moduledoc """
  Webhook base object: only available for the version 2 webhook.
  """

  @derive [Poison.Encoder]
  defstruct [
    :url,
    :auth_user,
    :auth_password,
    :events
  ]

  @type t :: %__MODULE__{
          :url => String.t(),
          :auth_user => String.t(),
          :auth_password => String.t(),
          :events => [String.t()]
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.Webhook do
  def decode(value, _options) do
    value
  end
end
