# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.WebinarRegistrant do
  @moduledoc """
  Webinar registrant.
  """

  @derive [Poison.Encoder]
  defstruct [
    :email,
    :first_name,
    :last_name,
    :address,
    :city,
    :country,
    :zip,
    :state,
    :phone,
    :industry,
    :org,
    :job_title,
    :purchasing_time_frame,
    :role_in_purchase_process,
    :no_of_employees,
    :comments,
    :custom_questions
  ]

  @type t :: %__MODULE__{
          :email => String.t(),
          :first_name => String.t(),
          :last_name => String.t(),
          :address => String.t(),
          :city => String.t(),
          :country => String.t(),
          :zip => String.t(),
          :state => String.t(),
          :phone => String.t(),
          :industry => String.t(),
          :org => String.t(),
          :job_title => String.t(),
          :purchasing_time_frame => String.t(),
          :role_in_purchase_process => String.t(),
          :no_of_employees => String.t(),
          :comments => String.t(),
          :custom_questions => [WebianrRegistrantCustomQuestions]
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.WebinarRegistrant do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :custom_questions,
      :list,
      ZoomAPI.Model.WebianrRegistrantCustomQuestions,
      options
    )
  end
end
