# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.WebinarPanelistList do
  @moduledoc """
  Webinar panelist.
  """

  @derive [Poison.Encoder]
  defstruct [
    :total_records,
    :panelists
  ]

  @type t :: %__MODULE__{
          :total_records => integer(),
          :panelists => [map]
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.WebinarPanelistList do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:panelists, :list, :map, options)
  end
end
