# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.WebinarPanelist do
  @moduledoc """
  Webinar panelist.
  """

  @derive [Poison.Encoder]
  defstruct [
    :panelists
  ]

  @type t :: %__MODULE__{
          :panelists => [Object]
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.WebinarPanelist do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:panelists, :list, ZoomAPI.Model.Object, options)
  end
end
