# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.WebinarInstances do
  @moduledoc """
  List of webinars.
  """

  @derive [Poison.Encoder]
  defstruct [
    :webinars
  ]

  @type t :: %__MODULE__{
          :webinars => [map]
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.WebinarInstances do
  import ZoomAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:webinars, :list, :map, options)
  end
end
