# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.ZoomRoom do
  @moduledoc """
  Zoom room.
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :room_name,
    :calender_name,
    :email,
    :account_type,
    :status,
    :device_ip,
    :camera,
    :microphone,
    :speaker,
    :last_start_time,
    :location
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :room_name => String.t(),
          :calender_name => String.t(),
          :email => String.t(),
          :account_type => String.t(),
          :status => String.t(),
          :device_ip => String.t(),
          :camera => String.t(),
          :microphone => String.t(),
          :speaker => String.t(),
          :last_start_time => String.t(),
          :location => String.t()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.ZoomRoom do
  def decode(value, _options) do
    value
  end
end
