# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule ZoomAPI.Model.ZoomRoomList do
  @moduledoc """
  Zoom Room List
  """

  @derive [Poison.Encoder]
  defstruct [
    :page_count,
    :page_number,
    :page_size,
    :total_records
  ]

  @type t :: %__MODULE__{
          :page_count => integer(),
          :page_number => integer(),
          :page_size => integer(),
          :total_records => integer()
        }
end

defimpl Poison.Decoder, for: ZoomAPI.Model.ZoomRoomList do
  def decode(value, _options) do
    value
  end
end
